# curl --location 'localhost:8080/token'
#--header 'Content-Type: application/json'
#--data '{
#    "username": "user",
#    "password": "password"
#}'
POST localhost:8080/token
Content-Type: application/json

{
  "username": "user",
  "password": "password"
}

###

